### ISSUE TITLE
Create a VS project system / flavour

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#19]
Create a Vs extennsion that adds a new project system to VS for creating DotNetNuke Extensions. This means it will show as a Project Type on the VS new project page. 

This is not a project template, this will be a fully blown project system / flavour.

The benefit of creating a project system over a simple project template is that I can integrate with VS to handle 'Run' and 'Debug' commands from the vs environment. 

This will mean a developer will be able to run their vs extension project by clicking the usual play button in Vs and watch as the dnm extension is packaged up and deployed to a dnn host website and the debugger then attaches. 

This new project system will still include a dependency on the DnnPackager nuget package which will contain all the custom build and deployment logic used by the project during builds to package up the dnn extension zip correctly etc. This has the benefit that I can still roll out improvements to these build tasks via releasing a newer nuget package, and people need not create new projects to get the latest build / deployment improvements, just update using nuget.

Links to resources for developing vs project systems to follow

**Comment by dazinator** [comment]
Have reached out: Microsoft/VSProjectSystem#75

**Comment by dazinator** [comment]
This is now underway in a seperate repo.

**Comment by nvisionative** [comment]
So awesome!  Thanks for all you are doing @dazinator
