### ISSUE TITLE
VS2015 and DnnPackager

### ISSUE THREAD

**Issue by mtrutledge** [dazinator/DnnPackager#20]
Darrell, We have upgraded to VS2015 and are starting a new DNN Module package. I want to use your DNNPackager because I subscribe to the same thought process you do. But VS2015 projects are so different. I added the DNNPackager nuget package, but I dont see the added files you reference on your gitgub page. Does it not work with VS2015 yet?

Also what is the best way to contribute to your project? Do you have any Dev guidelines?

**Comment by mtrutledge** [comment]
Scratch that. I created a Class Library (Package) Project instead of a regular Class Library. *facepalm*

**Comment by dazinator** [comment]
No worries! Glad you found a solution :-)
