### ISSUE TITLE
Support for producing "Sources" package.

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#21]
Currently, the install package produced does not contain source code files.

There should be the option to also produce a sources version of the install package.

This can work in exactly the same way as in it would include everything the regular install package includes, but it would also need to include source code files - which is currently any file in the project with one of the following extensions:

1. cs
2. vb

**Comment by nvisionative** [comment]
Agreed.  Thanks for adding this issue.  You beat us to the punch!  ;-)

**Comment by nvisionative** [comment]
Oh, you'll also need to consider adding the following:

* sln
* csproj
* vbproj
* targets
* xml
* nupkg
* xsd
* proj
* ps1
* psm1

There may be others, but these were some off the top of my head.

**Comment by dazinator** [comment]
Ok - cheers. I'll look to include these by default, and allow this list to be overriden.
I guess I should also include any project item with a build action set to "compile".

**Comment by dazinator** [comment]
This is currently waiting on #15 to be finished and merged back to master, before I can start on this issue.

**Comment by nvisionative** [comment]
Awesome - thanks!

**Comment by nvisionative** [comment]
@dazinator how is this one coming along?

**Comment by dazinator** [comment]
Have been sidetracked by the project system work im doing for a while, but I'll try and pick this one up over the next couple of weeks!

**Comment by nvisionative** [comment]
Okay, I have a presentation for DNNCon Baltimore 2016 that is built around using DnnPackager and would love for this to be available before then.  If not, no biggie.  I just know it will be something I'm asked about and may be perceived by many as a barrier for using DnnPackager.

**Comment by dazinator** [comment]
Ok yeah good thinking. I'll try to get this out before then if possible.

**Comment by nvisionative** [comment]
Thanks!

**Comment by dazinator** [comment]
Just wondering.. if there is an example of a sources zip somewhere.I can't remember whether it's meant to also contain all the things an install zip contains such as assemblies and pdb's etc - or should it just contain source files only?

**Comment by dazinator** [comment]
And also, I'm wondering if the source files should be put in a seperate folder inside the zip, i.e like a "source" folder, or perhaps be an additional resource zip inside the zip? I guess I need some examples of  these source packages

**Comment by dazinator** [comment]
This seems to mention that the source is included as a resources zip inside the zip: http://www.dnnsoftware.com/forums/threadid/16719/scope/posts/is-the-source-zip-correct

**Comment by dazinator** [comment]
Ok think I have got my head around this now.

**Comment by dazinator** [comment]
I'm not sure it makes sense to include the .csproj file. You may have project items in your project that you do not wish to be distributed in the zip package. The project file may also be referencing build targets, or have project references, nuget package references etc for things that you don't include inside the zip package. Therefore if you just include the .csproj file as is inside the sources zip, theres a good chance that people won't be able to open this project file "as is" once extracted from the sources zip - as there may be missing files, missing project references, missing nuget packages, missing targets files etc etc.. Does anyone actually do this?

**Comment by nvisionative** [comment]
Please review https://github.com/ChrisHammond/DNNTemplates/blob/master/VSIX/CSharp-DAL2-Template/BuildScripts/ModulePackage.targets - this is what people expect.

**Comment by dazinator** [comment]
Thanks @nvisionative. I need to understand more fully about the reasoning behind these sources packages, as I don't just want to blindly copy Chris Hammond. From what I can currently see, the sources packages are way to install a module into a dnn site, but also include the code behind files etc, so that for modules that use Dynamic Compilation in IIS, people can essentially do into the folder (on disk) modify some code directly in a website folder where the module is installed, and then the site will restart, the module will be dynamically compiled, and the changes will be reflected on the site. This is completely different from distributing a VS solution to VS developers that will build, compile, run etc. Therefore at the moment I can't see any benefit to including a csproj file or sln file in the "sources" package..

**Comment by nvisionative** [comment]
By the way, that 2006 forum post you referenced was related more to someone trying to find the source code for an old core module (DNN Store) - not how Source install packages should be built. Chris Hammond's module templates are the de facto standard.

**Comment by dazinator** [comment]
I hav epretty much completed this feature, but for now i'm not including csproj, or sln files as I believe that to be correct, even though Chris Hammonds stuff does include them, I don't think it's a good idea for the present!

**Comment by nvisionative** [comment]
That all depends on the compilation method chosen by the developer.  I definitely believe you should follow Chris' lead on this.

**Comment by dazinator** [comment]
Thanks @nvisionative I do appreciate and value your advice on this, but I'll have to address including the csproj, sln files as a seperate issue. I personally think it's a mistake and I'd love to see any example of this working or being used successfully to distribute projects / solutions to developers. I personally think what would happen is someone would go to open the csproj file / sln file and hit multiple issues that they'd have to fix before they could use it in VS..

**Comment by dazinator** [comment]
I have blogged about this stuff here if interested: http://darrelltunnell.net/blog/2016/03/19/dnn-extensions-sources-packages-what-are-they/
