### ISSUE TITLE
Add support for SPA and MVC development for DNN 8

### ISSUE THREAD

**Issue by nvisionative** [dazinator/DnnPackager#22]
With DNN 8 launching very soon, it would be fabulous to add support for SPA and MVC development.  Please see https://github.com/jbrinkman/DNN8Templates (temporary location) for more insight.

**Comment by dazinator** [comment]
DnnPackager should just continue to work as normal, although I will test it out.

The reason I say that is that, unless I am missing something, nothing looks to be changing regarding how modules are packaged up, and how they are installed.

When you add DnnPackager, it just adds the msbuild logic to your project to ensure the install package is produced, and it also adds the deployment command to the package manager console in VS so you can deploy your module to your local dnn instance easily. However in terms of what development methodology you use to actually develop your module, that's currently left down to you - i.e you have to add the required references, javascript etc etc. I think what is needed here are some official Dnn NuGet packages that can be added to a project to set you up for your development paradigm.

For example, if there was a DotNetNuke.Mvc Nuget package that included the required dll's, content files etc - you would just add the following NuGet packages to a new project:

1. DnnPackager
2. DotNetNuke.Mvc

If however you wanted to develop and SPA  you'd add

1. DnnPackager
2. DotNetNuke.Spa

This will require that someone create those appropriate NuGet packages though, assuming they don't allready exist.

Let me know if I am missing something here, and what you think of the above.

**Comment by dazinator** [comment]
I have [raised an issue here](https://github.com/jbrinkman/DNN8Templates/issues/2) if you are interested, although i'm not really sure if I have raised it in the right place :)

**Comment by nvisionative** [comment]
I just made a pull request to support DNN 8 SPA and MVC development.  These are very minor changes and as far as I can see the only changes you need to make other than updating your Getting Started blog.  I will also chime into your conversation with Joe.  Glad you did that!

**Comment by dazinator** [comment]
Cheers for the PR, i'll assume this closed for the time being. Feel free to re-open if anything further crops up.

**Comment by nvisionative** [comment]
You rock - thanks!
