### ISSUE TITLE
Support .dnnX manifest files

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#27]
Developers can create an install package that can be installed into multiple different versions of DNN. The format of the manifest file has changed slightly from version to version though. To allow developers to keep a single install package but take advantage of all the features of the manifest allowed for the target DNN version, DNN allows you to include version specific manifest files in the package.

See here for more details: http://www.dnnsoftware.com/community-blog/cid/134615/the-dnn6-extension-manifest-file

This means DnnPackager should support allowing not only a manifest.dnn file, but also version specific manifest files.

**Comment by dazinator** [comment]
I am working on this in dev branch for next version

**Comment by dazinator** [comment]
You can now also add `manifest.dnn[VersionNumber]` in your project, and these will be included in the install zip.

For example you could have:

- manifest.dnn
- manifest.dnn5
- manifest.dnn7

You can also add build config specific ones that will be preferred by default if they are present for current build config:

- manifest.dnn
- manifest.debug.dnn
- manifest.release.dnn
- manifest.dnn5
- manifest.debug.dnn5
- manifest.dnn7
- manifest.release.dnn7

So, given the above, if you build in release mode, the install package would include:

- manifest.release.dnn
- manifest.dnn5
- manifest.release.dnn7

**Comment by dazinator** [comment]
Documented on wiki page: https://github.com/dazinator/DnnPackager/wiki/Manifest-Files

**Comment by nvisionative** [comment]
Does DNN have an awareness to build config specific versions of the manifest file?  If so, I was completely unaware of this.  Guess you learn something new everyday!  ;-)

**Comment by dazinator** [comment]
DNN doesnt't really care about debug or release manifests when you install the zip. It only cares about the manifest for the current version (if there is one) ending in .dnn[version], or if there isn't a manifest for the matching dnn version then it will just use the manifest ending in .dnn.

The debug / release (build configuration) version of the manifest is purely a DnnPackager thing that about which manifest file actually ends up in the install zip based on the build configuration i.e debug / release.  The reason its there is in case you want the manifest to install different files depending on the build configuration its built under. For example suppose you want to include additional pdb files in the manifest when you do a debug build of your zip, but when you do a release build you want a manifest that doesn' list those files, and perhaps it references a different licence file or something. In that instance you could create a debug version and a release version of the your manifest, and the appropriate one will be included in the install zip when you do a build.

Its a little bit confusing, but it came in as a handy feature for me on a few occasions, and its purely optional as you'd only create these manifests if you need the feature for some reason! :-)

**Comment by nvisionative** [comment]
Ah, that makes sense now and is a great idea.  Thanks!



On Mon, Dec 14, 2015 at 6:16 PM -0800, "Darrell" <notifications@github.com<mailto:notifications@github.com>> wrote:


DNN doesnt't really care about debug or release manifests when you install the zip. It only cares about the manifest for the current version (if there is one) ending in .dnn[version], or if there isn't a manifest for the matching dnn version then it will just use the manifest ending in .dnn.

The debug / release (build configuration) version of the manifest is purely a DnnPackager thing that about which manifest file actually ends up in the install zip based on the build configuration i.e debug / release. The reason its there is in case you want the manifest to install different files depending on the build configuration its built under. For example suppose you want to include additional pdb files in the manifest when you do a debug build of your zip, but when you do a release build you want a manifest that doesn' list those files, and perhaps it references a different licence file or something. In that instance you could create a debug version and a release version of the your manifest, and the appropriate one will be included in the install zip when you do a build.

Its a little bit confusing, but it came in as a handy feature for me on a few occasions, and its purely optional as you'd only create these manifests if you need the feature for some reason! :-)

-
