### ISSUE TITLE
Package / Manifest Validation

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#28]
DnnPackager is in the unique position to do some validation on your manifest / install package at build time, and perhaps output warnings during the build.

Some checks that it could do might be:

1. Have you included a release notes file?
2. Have you included a licence file?
3. If you have specified the above files in the manifest, have you actually included those files in the package / your project - because otherwise DNN will fail the install.

**Comment by nvisionative** [comment]
These sound like great enhancements!
