### ISSUE TITLE
Auto Attach Debugger

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#29]
Having to do the `ctrl + alt + p` milarky to attach to the correct workerprocess to debug is time consuming.

I am going to extend the `Install-Module` command with an additonal `Attach` argument that will automatically attach your vs instance to the website worker process after the modules are successfully deployed.

So to use this feature, in the package manager console, you'd type something like:

```
Install-Module "MyDnnWebsite" --Attach
```

**Comment by nvisionative** [comment]
Okay, that is freakin' awesome!  You rock dude!

**Comment by dazinator** [comment]
Haha.. I try my best!

**Comment by nvisionative** [comment]
Do you have any time available next week for an online meeting?  I'd like to run an idea by you and would be best to discuss rather than trying to go back and forth here.

**Comment by dazinator** [comment]
Yeah I can make some time to discuss something, evenings are best for me. There is also a gitter chat room set up (sent you a link hopefully). I don't have a webcam so video during meetings is not going to be an option for me at present. I do however have a microphone so if you prefer voice communication, send me through an appropriate meeting invite for your meeting client of choice!

**Comment by dazinator** [comment]
This is fixed as of v2.

**Comment by nvisionative** [comment]
Thanks!  I have joined the chat.  We can try to discuss there.  I am not sure what our timezone difference is, but I am EST (UTC -5:00).  I can try to work around your schedule.
