### ISSUE TITLE
Enable Publish to a Store?

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#32]
Investigate possiblity of publishing your module to the DNN store (or my own??) via something like:

`Publish-Module [ModuleName] [AccessToken / Username / Password] `

This would build and then upload your package to the store.

I have a feeling the DNN store may not have an API for this kind of thing. So potential to create a basic store website on azure, that allows people to mamage their packages similar to NuGet.org but for DNN modules / extensions.

**Comment by nvisionative** [comment]
To my knowledge the DNN Store has no such capabilities.  Instant Order Notification (ION) is about the most advanced feature I am aware of.  

For what it is worth, I'm thinking this may be nice, but perhaps the "wrong tool for the job".  Consider the required "meta data" that would have to be handled when it comes to your module "product" in a store, this may be a bit confusing or abnormal at the least to handle via Visual Studio / NuGet.  

That said, this could definitely be pulled off technically with a store implementation using a system like Hotcakes.  I am just not convinced this is right way to approach it and there a ton of potential "gotchas" to consider.

**Comment by dazinator** [comment]
Yeah you are

**Comment by dazinator** [comment]
To elaboralate a little, i am inspired by chocolatey. NuGet came along and allowed developers to package up their libraries, and also publish them to a NuGet feed (store). Dev teams love this because they can automate their release workflows. Chocolatey came along and used the same model and even NuGet package format but allows dev teams to package up entire applications and publish them to a store. This is basically the same idea but for Dnn extensions. The manual effort of maintaining releases on the Dnn store must not be negligible. Im not decided yet but i think there is potential in this space somewhere..

**Comment by nvisionative** [comment]
I certainly hear where you are coming from.  Just knowing the ecosystem, being a module vendor in Snowcovered and ultimately DNN Store for years, it is a clunky process at best.  Some module developers are OSS all the way and others sell their commercial modules.  Some of them publish to GitHub.  Some of them publish to CodePlex.  Some of them publish to DNN Forge.  Some of them publish to DNN Store.  Some of them publish to their own website stores using a plethora of cart modules (e.g., Smith Cart, Cart Viper, CATALooK, RevIndex, Hotcakes, etc.).  And there's more, so it is really all over the place.  I personally would love to see a more solid release workflow as a standard.  I just think it is a tall order, especially for commercial module developers.

**Comment by dazinator** [comment]
Haha.. damn thats a lot of different publishing options

**Comment by dazinator** [comment]
You have convinced me to forget about this for the time being. I dont need another mammoth projevt just now anyway ;)

**Comment by nvisionative** [comment]
LOL - yeah, good idea, but a "can of worms" project for sure!
