### ISSUE TITLE
Rework install of targets files 

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#33]
At the moment, there is a custom install.ps1 powershell script in the NuGet package that makes alterations to the project file in order to add the DnnPackager targets, and this has logic to detect octopack so that if octopack targets are present, then the DnnPackager target is added before the octopack target. This allows DnnPackager to automatically set OctoPack MsBuild variables if OctoPack is present so for example, it can set the OctoPack version number for the NuGet Package to be the Dnn version number in the module manifest.

However OctoPack is really not necessary for NuGet packaging and this is complicating the install process quite a bit. There are simpler ways to package up your modules as NuGet packages for deployment purposes, so lets look to remove this octopack stuff from the install script.

Can look to adopt the following to let NuGet handle installing the targets into the project instead? https://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project

**Comment by nvisionative** [comment]
I was curious about the OctoPack stuff - glad to hear it may not need to be there after all.
