### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Swoogan** [dazinator/DnnPackager#4]
After adding the nuget to my project and building, I get the following error:

> Description: The imported project "...\packages\DnnPackager.1.0.2\.build\MSBuild.Community.Tasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  ...\packages\DnnPackager.1.0.2\tools\DnnPackager.targets	

> File: ...\.nuget\NuGet.targets

The `.build` folder is in the folder with my solution file, not in the `packages\DnnPackager.1.0.2` folder.

The project seemed to build and I have a zip file in the `InstallPackages` folder.

**Comment by dazinator** [comment]
Thank you for taking some time to create an issue on github :)

I am not able to replicate this issue but some thoughts spring to mind.

Could you let me know the following:

1. What version of Visual Studio are you using? (if you are using less than 2013, can you try closing VS then re-opening and reloading the solution, then building to see if the problem persists?)
2. What project type do you have, and what .net framework version is it targeting? 

Many thanks

**Comment by Swoogan** [comment]
So I realized after posting that the error was coming from NuGet.targets. We were using the old NuGet package restore implementation for building packages. I'm not sure if it was the building of the packages or the restoring of them that threw the error. I eliminated it by removing all the NuGet stuff since I'm trying to use your mechanism.

**Comment by dazinator** [comment]
Ah ok - glad to hear you made progress with it. Let me know if anything else crops up. :)

**Comment by dazinator** [comment]
I'll assume there is nothing further to do here - closing.
