### ISSUE TITLE
Missing iconFile node in manifest

### ISSUE THREAD

**Issue by nvisionative** [dazinator/DnnPackager#40]
The manifest file is missing the iconFile node.

**Comment by dazinator** [comment]
Not sure if you are aware, but when you create a PR, you only need to create it once, and any more commits or changes you make will automatically appear in that PR - i.e you don't have to create another PR after each new change / commit - Not sure if that is what has happened but there was about 7 PR's in the end all seeming to contain the same changes. Have been through and closed them ;)
