### ISSUE TITLE
SolutionBuildPackagesFolder is never removed

### ISSUE THREAD

**Issue by Swoogan** [dazinator/DnnPackager#5]
The `CleanPackages` target in `before.JE.D2D.Modules.sln.targets` doesn't appear to be called at all.

**Comment by dazinator** [comment]
You are right.

This stems from the fact that when you build through VS, the `before/after.*.sln.targets` are not invoked. This is documented out there on the internet, and there is no way around it.

They are only invoked, when you build the solution using MsBuild.exe directly.

Fortunately, pretty much all build servers I can think of use an MSBuild runner (i.e they invoke MSBuild.exe) directly - so you will find that for build server builds, these targets will be invoked, and the folder will be cleared.

However for local Visual Studio builds - I still need to find a solution for this. There doesn't seem to be anyway of running an msbuild task once at the start of the build, and once at the end (when building locally within VS).

I will try to look at this in some more depth when I get some time :)

**Comment by dazinator** [comment]
- Are you actually seeing any detrimental effects due to this target not running on local VS builds? i.e are you getting incorrect zip packages etc?

**Comment by Swoogan** [comment]
I am calling it from the command line with msbuild. I'm probably just missing a switch or something. I'll re-read the docs. Here is the command I am using:

    C:\...\Src\Modules>msbuild Modules.sln /p:CreateSolutionDeploymentPackage=true
    /p:NuGetExeFilePath=".nuget\NuGet.exe" /p:SolutionPackageVersionNumber=2.3.0.0

**Comment by dazinator** [comment]
hmm.. did you per chance, happen to rename your solution file from "JE.D2D.Modules.sln" to just "Modules.sln" ? 

I believe the 2 targets files have to be named the same as the solution i.e before.[solutionname].sln.targets - so perhaps when you installed DnnPackager, it created those 2 files based on your solution name, but then when you renamed the solution, it hasn't renamed the 2 targets files to keep them in line?

**Comment by Swoogan** [comment]
No. Sorry, I was trying to obfuscate the solution name to protect the innocent.
