### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by Lukejkw** [dazinator/DnnPackager#56]
Hi,

Not sure if it is just me but I cannot seem to deploy my module Running the command Install-Module Fidelity(my website name in IIS).

**Keep getting the following:**
PM> Install-Module Fidelity
Executing build --envdteversion 14.0 --processid  6316 --configuration  --name Fidelity --websitename Fidelity 
Could not parse arguments: 
arg 0, value enclosed in double asterix: **build**
arg 1, value enclosed in double asterix: **--envdteversion**
arg 2, value enclosed in double asterix: **14.0**
arg 3, value enclosed in double asterix: **--processid**
arg 4, value enclosed in double asterix: **6316**
arg 5, value enclosed in double asterix: **--configuration**
arg 6, value enclosed in double asterix: **--name**
arg 7, value enclosed in double asterix: **Fidelity**
arg 8, value enclosed in double asterix: **--websitename**
arg 9, value enclosed in double asterix: **Fidelity**
Dnn Packager
DnnPackager 2.0.6+2.Branch.master.Sha.e50957a2c76e82b58f563ad53fff78bded5c57c1
Copyright c Darrell Tunnell 2015

  --deploy             Deploy packages to a local DNN website in IIS.

  --build              Build a visual studio project and deploy the packages to
                       a local DNN website in IIS.

  --install-targets    Install the DnnPackager targets to a visual studio 
                       project file.

  --help               Display this help screen.

Where am I going wrong here?

**Comment by dazinator** [comment]
Hi there!

Thats odd. When you issue that powershell command it calls dnnpackager.exe passing necessary args accross. However for some reason, possibly a bug, in your scenario, arg 5 (--configuration switch) is meant to be followed by your active VS build configuration for the solution (debug / release etc) but in your case that argument isnt being sent accross.

I will try and repro this, in the meantime, can you try providing the build config value explicitly by using:

`Install-Module Fidelity Debug`

It may also be worth just double checking your build configuration settings in vs for anything odd. 

Lastly, what version of VS are you using?

**Comment by Lukejkw** [comment]
Howdy! Thanks for such a speedy reply. 

I thought as much. Providing the build config explicitly works. Before your advise, I manage to get it working using `Install-Module Fidelity Release`. `Debug` is handier though :)

I am using VS 2015 Enterprise. Nothing looks funny in my build configuration but I will keep playing to see what I can find.

**Aside:**
Thanks for the hard work. I have always hated the DNN module templates and tight coupling between the DNN install and the code project. Especially considering that I mainly build one off extensions for clients with a particular need. Haven't really had to play much with the .dnn configuration files but might aswell configure my view using XML than through _that_ extension manager UI.

Luke

**Comment by dazinator** [comment]
Hi @Lukejkw !
Thanks :) 

I have made some tweaks and think this should now be fixed in the latest version (development branch)

I have attached a zip containing the latest NuGet package if you wanted to try it out, otherwise you can just wait until the update appears on the official NuGet feed and then give it a go that way!

I'l leave this issue open until then.

[DnnPackager.2.1.0-unstable0068.zip](https://github.com/dazinator/DnnPackager/files/254027/DnnPackager.2.1.0-unstable0068.zip)

**Comment by Lukejkw** [comment]
Hi @dazinator 

Thanks, I will give it a test when I get a chance and let you know.

Luke

**Comment by dazinator** [comment]
Closing this now, re-open if you still experience issues!
