### ISSUE TITLE
Add module.css file

### ISSUE THREAD

**Issue by david-poindexter** [dazinator/DnnPackager#59]
@dazinator it would be great for DnnPackager to add module.css initially for module development.  I suppose this would not be relevant for theme development, so not sure what to recommend there.  :)

**Comment by dazinator** [comment]
Hmm, I think I'll leave this one to be taken care of the project system I am working on, so when creating a "Module" project, it will add that file by default, but not for the other project types like Library etc.. Would be too hard to introduce it at this level as you have mentioned its not suitable for all projects that DnnPackager might be added to.

**Comment by david-poindexter** [comment]
Makes sense - thanks!
