### ISSUE TITLE
Install-Module fails due to new security measures implementated

### ISSUE THREAD

**Issue by david-poindexter** [dazinator/DnnPackager#61]
@dazinator we now have an issue related to the new security measures implemented in DNN.  See [Critical Security Update](http://www.dnnsoftware.com/community-blog/cid/155362/critical-security-update--please-read).  Starting with DNN 08.00.03, ~/Install/Install.aspx no longer exists.  That said, there is obviously still a mechanism by which to install modules because the "Available Modules" still works via Host > Extensions.  Perhaps some additional research is in order.

**Comment by dazinator** [comment]
Hmm, yeah. This might lead me further down the path of creating my own module to install into Dnn to act as the remote installer (i.e it would host some form of WebApi). This would mean that developers would have to manually install this 1 module to begin with, but then from then on, DnnPackager would happily deploy the module using those webservices, rather than the ~Install/Install.aspx mechanism.

I wouldn't be surpised if the installation code under "Available Modules" can only be triggered via a 'POST` request, as it's probably a module on that page that does it, and this means that it's gonna reuqire all sorts of state in that post request like appropriate authentication cookie and anti forgery tags etc etc. If that is the case, this will probably eliminate it as a viable mechanism as far as DnnPackager would be concerned.

**Comment by david-poindexter** [comment]
I have alerted @jbrinkman and hopefully he'll have some ideas for remediation.

**Comment by dazinator** [comment]
Thanks. It's a shame the bulk installer couldn't be enabled for development instances, and just defaulted to disabled, rather than completely removed from the product :(

**Comment by david-poindexter** [comment]
I agree @dazinator - I hope @jbrinkman can help in this area.  For now, we have the option of developing against pre-DNN 08.00.03, but this is not ideal moving forward.

**Comment by david-poindexter** [comment]
Any progress on this?  I have heard nothing more from @jbrinkman.  I was hoping he could help shed some light.  Any ideas @hismightiness?  This is a real bummer for those of us that have adopted the DNN Packager way of doing things.  Someone with a bit more knowledge of possibilities within the core may be able to help.  I'll tag a few folks here to see if they have ideas.  @cartersolutions @mitchelsellers @ohine @bdukes @donker

**Comment by dazinator** [comment]
I've not made any progress on this as yet i'm afraid. I'm willing to accept any PR's or suggestions on possible ways forward. Will see what the community can suggest :-)

**Comment by ohine** [comment]
We could easily add a check for Host > Debug, and if it's disabled (default setting), then the install/install.aspx file could exit out gracefully. Another option would be to add an authentication check (something I've asked for a few years now), so that install/\* only functions for authenticated users. Very similar to the upgrade authentication prompt. Not sure which method would be preferred. I'd be happy to do the pull request if @jbrinkman can let us know which option would be accepted into the core.

**Comment by david-poindexter** [comment]
Thank you @ohine for chiming in - great suggestions!  @jbrinkman - I know you are busy, but could you give Oliver some feedback on this?

**Comment by lepigocher** [comment]
@dazinator for development instances, you can extract deleted files from the archive! Not really practical but it works.

**Comment by dazinator** [comment]
@lepigocher - not sure I follow, can you elaborate?

**Comment by lepigocher** [comment]
@dazinator - At the end of install or upgrade, DNN 8.0.x delete code files from the \Install folder. Open the dnn install or update zip file of the same version you used for install or upgrade your instance, then extract the missing files (Install.aspx, Install.aspx.cs, ...) to the Install folder! This way you get back the original instance as just before install/upgrade. The new process simply delete those files after the install/upgrade when your instance restart, that's all.

**Comment by dazinator** [comment]
Oh I see, so you can just put the install wizard back and it works?

If thats the case their might be the option of releasing the install wizard as an extension that can be installed into dev instances or instances where people dont mind the security implications?

**Comment by lepigocher** [comment]
Yep, but if you do that please specify in red bold 32px what you'r ready to install! ;-) Because some people could not really understand what they do by installing such module. Your comment was for development instance, that's why I told you to just 're-introduce' those files. In this case, there is no risk to expose your instance to the security issue encountered with recents versions of DNN! Otherwise, you expose this instance to serious security risk (creation of host account, ...).

**Comment by dazinator** [comment]
> Yep, but if you do that please specify in red bold 32px what you'r ready to install! ;-) 

Haha.. If we did do this, we could host the install zip here on a github page --> and put a massive disclaimer FOR DEVELOPMENT USE ONLY (NOT PRODUCTION!).

I think the longer term solution is basically what @ohine said, which is to add authentication into the mix. It would be great if Dnn had a Web API that you could authenticate with and perform basic administrative functions, like managing extensions. Having an automation tool that updates a system by dumping zips into a directory and then calling a URL and monitoring the directory to detect when all extensions are installed is not the slickest integration story.

**Comment by lepigocher** [comment]
Hi @dazinator, Agreed, the solution proposed by Oliver is what DNN Corp should do! In the meanwhile, can you explain your problem, because I do not understand!? Create a WepAPI is really simple and to install a module when you know the path of the package file it's just one line of code! Did you looked at the source of the modules Install.ascx and BatchIntall.ascx in the folder \DesktopModules\Admin\Extensions? To install a module you have to call the static method Upgrade.InstallPackage(string file, string packageType, bool writeFeedback) from the namespace DotNetNuke.Services.Upgrade.

**Comment by dazinator** [comment]
@lepigocher 

> can you explain your problem, because I do not understand!?

Sure. DnnPackager is a seperate executable. It doesn't run inside Dnn. Prior to the security update there was a way (All be it not ideal) that an external process such as DnnPackager, Team City etc, could get an extension installed into a DNN website, calling the bulk install url.

The issue now, is that after the security update, there is no reliable way for an external process to do this anymore (unless you put the install wizard back haha and re-introduce the security risk that has been present all these years).

I was toying with the idea of creating a Dnn extension, to host a proper web API as per my comments above:

> Hmm, yeah. This might lead me further down the path of creating my own module to install into Dnn to act as the remote installer (i.e it would host some form of WebApi).

And yes, this would allow DnnPackager to more reliably execute a package install, and yes I have looked at the install code and, like you say, it's not hard,

However the problem with that is that people will then have to install this additional module / extension into Dnn before they can use `DnnPackager`. In my view, it would be better for such an API to be baked into Dnn out of the box. This would allow for a variety of automated tools out their to integrate and perform deployments securely, to a Dnn instance, out of the box.

For example, if you have a TeamCity build, and as part of that process you want to deploy your extensions to a CI environment - this is much easier if DNN has a standard web api to authenticate against to do a package deployment securely, out of the box. If you use Octopus Deploy, doesn't matter - its the same API you would use. DnnPackager? No problem, use the same API. 

Presently, AFAIK this API doesn't exist, and functionality has now been lost as a result of the update. I think we need a replacement but I don't think it should necesssarily come from DnnPackager..

But we shall see what happens. I'd like to know what other folks think, and if there is any work already planned around this area --> I try to be as lazy as I possibly can be these days :)

**Comment by david-poindexter** [comment]
I agree 100% @dazinator.  Perhaps this warrants a JIRA ticket and subsequent pull request to DNN Platform.

**Comment by lepigocher** [comment]
@dazinator I totaly agree with you but this feature as well as others (page management, module management an so on) have been discussed for several years by many MVP and well know members! Even CMIS was mentioned (see: https://en.wikipedia.org/wiki/Content_Management_Interoperability_Services). I don't know if we will have any of this a day... :-(

**Comment by bradbamford** [comment]
So is DnnPackager essentially dead now, moving forward, as far as the auto-install attach part?

**Comment by dazinator** [comment]
I wouldn't say dead, but if you want to use this feature with latest Dnn 8
or above then you'll have to install the old admin "Installer" module back
that the latest security patch removed. I think the longer term solution is
that DnnPackager needs its own Dnn Module that can be installed to act as
an "agent" which it can then talk to via its WebApi to handle deployment of
install packages.
Contributions would be very welcome if someone out there wants to see that
happen!

**Comment by david-poindexter** [comment]
Dnn Packager works fine up to DNN 8.0.2.  Starting woth 8.0.3, it will not work.

**Comment by dazinator** [comment]
I recently found a better approach for installing a package, that should resolve this issue. It doesnt require any http calls or any modules to be installed in the dnn instance. I'll look to release a new version of dnnpackager in the near future.

**Comment by david-poindexter** [comment]
Nice, what did you discover?

**Comment by dazinator** [comment]
I discovered a way to use the DotNetNuke assemblies, from outside of the website. Basically I can now write a Dnn Cli, including commands for installing packages to dnn websites.

If you want more info: https://bitbucket.org/dazinator/dnncli

**Comment by david-poindexter** [comment]
Very interesting sir - well done!  Is this in the latest version of DnnPackager or is it forthcoming?

**Comment by dazinator** [comment]
Forthcoming - i'm just proving the process elsewhere at present.

**Comment by mtrutledge** [comment]
@dazinator Any update on the tool since the Install.aspx file has been removed?

**Comment by dazinator** [comment]
Not at present, the current guidance is to install the required files back into your local dnn development instance for the time being. I have proved a mechanism for installing a module that doesn't require `Install.aspx` - however this mechanism hasn't made it's way into DnnPackager as of yet.

**Comment by dazinator** [comment]
I am in the process of a new release. As of dnn 8, dnn packager will use a new method to install the packages, to workaround the lack of installwizard. Will post here when new release is available, just in the process of moving the build to appveyor from my private build server.

**Comment by david-poindexter** [comment]
That is great news @dazinator - thank you!

**Comment by mtrutledge** [comment]
very exciting news

**Comment by dazinator** [comment]
solved in v3 release

**Comment by RichardHowells** [comment]
> I discovered a way to use the DotNetNuke assemblies, from outside of the website. Basically I can now write a Dnn Cli, including commands for installing packages to dnn websites.
> 
> If you want more info: https://bitbucket.org/dazinator/dnncli

Hi,

I'm really interested in that code, but the link does not work any more.  (I get a message - "That link has no power here!" off the bitbucket site.)

Has it moved elsewhere?  Or may I get my hands on it some other way?

Thank you.
