### ISSUE TITLE
Multiple Modules in One Solution

### ISSUE THREAD

**Issue by bradbamford** [dazinator/DnnPackager#63]
I've been working on creating a single solution that contains all the modules that I frequently update.
It makes it a lot simpler for me rather than having multiple instances of VS running.

What would I need to modify in the powershell scripts so that DNNPackager looks at the Module Projects rather than the entire Solution?

**Comment by dazinator** [comment]
@bradbamford not sure what you mean, could you elaborate a bit?

**Comment by bradbamford** [comment]
Basically for each module I make, I create a new solution and add DNNpackager just like everyone else. 
However, I then add that project as a linked project to another Solution that contains all my modules and other supporting projects that I use in many of my modules. 
In this solution, DNNpackager will build the install zip files correctly on Build, but will not deploy using install-module because the PowerShell scripts are looking in the wrong path. I was thinking If I could modify the PowerShell scripts to look at the project paths instead of the solution paths that I might be able to get out to work.

**Comment by dazinator** [comment]
Got ya!
Not sure why that doesn't work. 
The powershell function is here: https://github.com/dazinator/DnnPackager/blob/master/src/DnnPackager/tools/ModuleDeployment.psm1#L10

I'm guessing perhaps it's not formulating the path to the DnnPackager.exe correctly in your scenario. If so you might wish to spruce up that method on the line I have highlighted. Will be interested to see what you come up with! Feel free to send a PR!

**Comment by dazinator** [comment]
For the v3.0 milestone release, I am scrapping the powershell commands. The new method will look at all projects in the solution, and find all install zips, and will deploy the lot.
