### ISSUE TITLE
Csproj depends on Nuget package being installed locally. 

### ISSUE THREAD

**Issue by gravidThoughts** [dazinator/DnnPackager#67]
```
{path}\xxx.csproj : error  : The imported project "{path}\packages\DnnPackager.2.0.6\tools\DnnPackager.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  {path}\xxx.csproj
```

Because of this dependency, users getting the project for the first time locally have to go in and modify csproj in order to be able to open it.

Is there a cleaner way to reference the props file?

BTW, thanks. This is so much better than the other available templates.

**Comment by dazinator** [comment]
Ah yes.. Ideally the `<import>` in the `csproj` should have a condition to check it exists, and should integrate with nuget restore. I'll flag this is a bug

**Comment by dazinator** [comment]
If you would like a workaround in the meantime, the only thing I can think of would be to check that nuget package in to your source control, which is a bit controversial with many setups ;-)

**Comment by gravidThoughts** [comment]
Workaround not a big issue for me, I am the only developer on this. I just thought I would point it out to you.

Thanks again for developing this package!

**Comment by gravidThoughts** [comment]
Also, this is the first time I have ever had an issue flagged as a bug. Should I leave it open?

**Comment by dazinator** [comment]
Haha lucky you! Yes please, you can leave it open.

Glad it's helping you out. If you like dnnpackager then you might be curious about a new Visual Studio project system I've been working on for over a year now. It's not ready for release quite yet but if you are curious you might like to [read this](http://darrelltunnell.net/blog/2016/01/17/imagining-a-dotnetnuke-project-type-for-visual-studio/)

**Comment by gravidThoughts** [comment]
I was looking at your code, thinking I may take my first crack at a pull request.
It appears you are adding the Import elements using the InstallTargetsHelper code.
[Nuget 2.5+ supports adding a Build folder which will automatically add the Imports to the csproj file with the conditional check for file existing.](http://sushihangover.github.io/nuget-and-msbuild-targets/)

May be something to consider.

**Comment by dazinator** [comment]
Thanks for delving in a bit further.
You are welcome to submit any PR around this.
The thing that stopped me from using the nuget mechanism were things like:

1. I import more than one props file. NuGet caters for single props and targets import which must be named the same as nuget package id.
2. I had some logic to check for existence of other targets / props and order them. For example projects that use octopack, the dnn packager targets must be imported before them. NuGet doesn't support this. 
3. During development, at one point, I renamed the targets / props files. Nuget doesn't know how to handle upgrades if the targets / props files change name from one version to another - I think I had some logic in the targets install method to check for old props / targets imports and remove them (or it may have been in the powershell install script, can't remember!)

However all that is largely legacy stuff now. I don't much care for octopack support anymore, and I'd love to just rely on nuget and scrap the custom install logic if possible. I doubt anyone uses old versions of dnnpackager anymore.

**Comment by dazinator** [comment]
I'll assign this to the v3.0 milestone.
For v3.0 I have simplified the targets / props installation by removing all of the custom powershell scripts, removed the solution level props and targets, and any octopack stuff. We allow nuget to install the build targets / props instead by placing them in the "build" folder of the nuget package.
