### ISSUE TITLE
DnnPackage keeps crashing

### ISSUE THREAD

**Issue by david-poindexter** [dazinator/DnnPackager#68]
It seems to be a common experience now when I load up a project, I see the following (right after the Package Manager Console prompt):

```
PM> DnnPackager: Solution post build targets file already exists. Overwriting..
DnnPackager: Solution before build targets file already exists.
DnnPackager: Imported DnnPackager Powershell CmdLets.
```

Then hitting the ENTER key produces this (in RED highlight):

```
DnnPackager: : The term 'DnnPackager:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ DnnPackager: Solution post build targets file already exists. Overwri ...
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DnnPackager::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 ```

Then executing any command just crashes DnnPackager.  Sometimes closing the solution and reopening "fixes" it for a while, but then it comes back.  This is really disruptive to our development flow.  ;-(

**Comment by dazinator** [comment]
Yeah, to be honest, dnnpackager has been a bit neglected and needs a new release as the powershell scripts are a bit flaky and not ideal. The text in the window that you have shown is produced by logging statements within the powershell install. so as a short term solution we can remove those logging statements from the powershell script and release a new version of dnn packager. In the meantime you can try as a workaround, clear the text in that window after opening the solution and before entering any command in for the first time. Everything after the `PM>` can be cleared. 

If a command continues to crash - feel free to attach details of that (copy of the text in the package manager console window would be useful) and I will try to investigate further.

**Comment by david-poindexter** [comment]
Thanks @dazinator - really appreciate the tool and will look forward to the next release!

**Comment by dazinator** [comment]
In V3.0 the powershell commands are going away. I'll assign this issue to the v3.0 milestone so it will close with the v3.0 release.
