### ISSUE TITLE
Scrap Powershell Commands, get "play" button working

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#71]

**Comment by dazinator** [comment]
NuGet dropped support for powershell scripts in nuget packages. Find a better away to provide Install / Debug capabilities that doesn't rely on powershell commands.

**Comment by david-poindexter** [comment]
Have you looked into going the route of NPM or Yarn instead?

**Comment by dazinator** [comment]
I'm trying to remove the need to run a script completely. Pressing the play button in VS is my goal. If I can't do that I will consider a script that you have to run and install with one of those tools.

**Comment by dazinator** [comment]
Approach I have used works by setting some startup arguments in project properties page.

**Comment by mtrutledge** [comment]
I know you want to go the route of press the play button and go, however a lot of developers are now moving away from a full fledged IDE like Visual Studio and are using code editors like VS Code and command line tools like NPM and yarn. It might be worth considering as a lower priority for the project.

Matt Rutledge

**Comment by david-poindexter** [comment]
@mtrutledge while that is indeed true, many of us still have the need to compile our projects using the full IDE.  Commercial modules, for instance, most of the time don't expose the source code in the shipped product.  Therefore, this is still a top-priority need in our opinion.

**Comment by dazinator** [comment]
@mtrutledge the popularity of vscode and other lightweight editors is definately not lost on me - you are right of course. As a longer term goal I will definately consider integration with those tools. As it stands the primary focus though is VS for the present.
