### ISSUE TITLE
Support 0.0.* for version in manifest

### ISSUE THREAD

**Issue by dazinator** [dazinator/DnnPackager#75]
Allow something like this in the manifest:

```xml
<package name="DnnPackagerTestModule" type="Module" version="0.0.*">
```

DnnPackager will auto increment the * portion on each build. It will do this by storing a temporary value (integer) somewhere so that it can be remembered between builds.

Probs best to use system temp directory for storing this value.

The idea, is that during development, as you make changes to the module and redeploy it, you can have dnnpackager auto increment the version for you. By doing this it ensures that when it is deployed, Dnn doesn't try and use cached install package from last time (it can do this if the package details / version number is the same between installs).

**Comment by david-poindexter** [comment]
You could alternately force a **Repair** install.  This allows you to keep the same version.  The above makes sense too though and may be a more solid approach.  :)

**Comment by dazinator** [comment]
Ah yes.. let me try that.. the old install url method did a repair automatically I beleive, but this new method I think I have to pass some additional options to enable that, will give it a try.

**Comment by david-poindexter** [comment]
Correct.  🥇

**Comment by dazinator** [comment]
Closing as repair option seems better than this feature
